name: fakhravari
description: "A new Flutter project."
publish_to: "none"
version: 1.2.2+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.0
  flutter_background_service: ^5.0.10
  sqflite: ^2.4.0
  path: ^1.9.0
  geolocator: ^13.0.1
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^18.0.1
  get: ^4.6.6
  device_info_plus: ^11.1.1
  unique_identifier: ^0.4.0
  app_links: ^6.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: IRANSansX_Regular
      fonts:
        - asset: assets/fonts/IRANSansX-Regular.ttf
    - family: IRANSansX_Medium
      fonts:
        - asset: assets/fonts/IRANSansX-Medium.ttf
